version: "3.8"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB}"
    volumes:
      - db-data:/var/lib/postgresql/data
  admin:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db-data:
